### ISSUE TITLE
HTTP Request to /timeTable failed

### ISSUE THREAD

**Issue by DeiEFLE** [apache/incubator-kie-optaplanner-quickstarts#109]
Hi,

I tried to get the 'quarkus-school-timetabling' example running.

Setup: 
Win10, 
eclipse 4.19.0, 
gradle 6.8

I went with 'live coding' and started the app with the gradle command as suggested in the readme.
When refreshing the browser the initial call to 'getTimeTable()' crashes.

I updated to the lates Quarkus, but the behaviour also appears with the version originaly used.

It seems like a Path is created from an URI causing the error. But I have no idea where the String comes from.
Please let me know, if I am doing anthing wrong, or if you have any further questions.

> \> Task :quarkusDev
> Listening for transport dt_socket at address: 5005
> \__  ____  __  _____   ___  __ ____  ______ 
>  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
>  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
> --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
> 2021-05-12 17:03:56,529 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-school-timetabling 0.1.0-SNAPSHOT on JVM (powered by Quarkus 1.13.3.Final) started in 10.427s. Listening on: http://localhost:8080
> 2021-05-12 17:03:56,531 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
> 2021-05-12 17:03:56,531 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, hibernate-orm-rest-data-panache, jdbc-h2, mutiny, narayana-jta, optaplanner, optaplanner-jackson, resteasy, resteasy-jackson, smallrye-context-propagation, webjars-locator]
> 2021-05-12 17:03:58,030 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-2) HTTP Request to /timeTable failed, error id: 9cab0c07-32cf-4f25-96f1-b5fbd435d416-1: org.jboss.resteasy.spi.UnhandledException: java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///C:/Users/USERDIR/.gradle/caches/modules-2/files-2.1/org.optaplanner/optaplanner-quarkus/8.6.0.Final/10931238061ea64a5cb4e4c9a28f0ef8efd7c85a/optaplanner-quarkus-8.6.0.Final.jar
> 	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
> 	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
> 	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
> 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
> 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
> 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
> 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
> 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
> 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
> 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
> 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
> 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41)
> 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
> 	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
> 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
> 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
> 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
> Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///C:/Users/USERDIR/.gradle/caches/modules-2/files-2.1/org.optaplanner/optaplanner-quarkus/8.6.0.Final/10931238061ea64a5cb4e4c9a28f0ef8efd7c85a/optaplanner-quarkus-8.6.0.Final.jar
> 	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
> 	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
> 	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
> 	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
> 	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
> 	at jdk.compiler/com.sun.tools.javac.file.FSInfo.getJarClassPath(FSInfo.java:112)
> 	at jdk.compiler/com.sun.tools.javac.file.CacheFSInfo.getJarClassPath(CacheFSInfo.java:93)
> 	at jdk.compiler/com.sun.tools.javac.file.Locations$SearchPath.addJarClassPath(Locations.java:423)
> 	at jdk.compiler/com.sun.tools.javac.file.Locations$SearchPath.addFile(Locations.java:413)
> 	at jdk.compiler/com.sun.tools.javac.file.Locations$SearchPath.addFiles(Locations.java:345)
> 	at jdk.compiler/com.sun.tools.javac.file.Locations$SearchPath.addFiles(Locations.java:333)
> 	at jdk.compiler/com.sun.tools.javac.file.Locations$SearchPath.addFiles(Locations.java:339)
> 	at jdk.compiler/com.sun.tools.javac.file.Locations$ClassPathLocationHandler.computePath(Locations.java:779)
> 	at jdk.compiler/com.sun.tools.javac.file.Locations$SimpleLocationHandler.setPaths(Locations.java:721)
> 	at jdk.compiler/com.sun.tools.javac.file.Locations.setLocation(Locations.java:2098)
> 	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.setLocation(JavacFileManager.java:927)
> 	at org.kie.memorycompiler.jdknative.NativeJavaCompiler.compile(NativeJavaCompiler.java:80)
> 	at org.kie.memorycompiler.AbstractJavaCompiler.compile(AbstractJavaCompiler.java:41)
> 	at org.kie.memorycompiler.KieMemoryCompiler.compileNoLoad(KieMemoryCompiler.java:130)
> 	at org.kie.memorycompiler.KieMemoryCompiler.compileNoLoad(KieMemoryCompiler.java:102)
> 	at org.kie.memorycompiler.KieMemoryCompiler.compile(KieMemoryCompiler.java:53)
> 	at org.kie.memorycompiler.KieMemoryCompiler.compile(KieMemoryCompiler.java:39)
> 	at org.drools.ancompiler.KieBaseUpdaterANC.inMemoryUpdate(KieBaseUpdaterANC.java:66)
> 	at org.drools.ancompiler.KieBaseUpdaterANC.run(KieBaseUpdaterANC.java:52)
> 	at org.drools.ancompiler.KieBaseUpdaterANC.generateAndSetInMemoryANC(KieBaseUpdaterANC.java:99)
> 	at org.optaplanner.core.impl.score.stream.drools.DroolsConstraintSessionFactory.buildKieBaseFromModel(DroolsConstraintSessionFactory.java:85)
> 	at org.optaplanner.core.impl.score.stream.drools.DroolsConstraintSessionFactory.buildSession(DroolsConstraintSessionFactory.java:126)
> 	at org.optaplanner.core.impl.score.director.stream.DroolsConstraintStreamScoreDirectorFactory.newConstraintStreamingSession(DroolsConstraintStreamScoreDirectorFactory.java:50)
> 	at org.optaplanner.core.impl.score.director.stream.DroolsConstraintStreamScoreDirector.resetConstraintStreamingSession(DroolsConstraintStreamScoreDirector.java:74)
> 	at org.optaplanner.core.impl.score.director.stream.DroolsConstraintStreamScoreDirector.setWorkingSolution(DroolsConstraintStreamScoreDirector.java:66)
> 	at org.optaplanner.core.impl.score.DefaultScoreManager.updateScore(DefaultScoreManager.java:45)
> 	at org.acme.schooltimetabling.rest.TimeTableResource.getTimeTable(TimeTableResource.java:66)
> 	at org.acme.schooltimetabling.rest.TimeTableResource_Subclass.getTimeTable$$superaccessor5(TimeTableResource_Subclass.zig:830)
> 	at org.acme.schooltimetabling.rest.TimeTableResource_Subclass$$function$$5.apply(TimeTableResource_Subclass$$function$$5.zig:29)
> 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
> 	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:63)
> 	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
> 	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
> 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
> 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
> 	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
> 	at org.acme.schooltimetabling.rest.TimeTableResource_Subclass.getTimeTable(TimeTableResource_Subclass.zig:788)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
> 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
> 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
> 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
> 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
> 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
> 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
> 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
> 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
> 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
> 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
> 	... 18 more
> 	Suppressed: java.lang.NullPointerException
> 		at org.optaplanner.core.impl.score.director.stream.DroolsConstraintStreamScoreDirector.close(DroolsConstraintStreamScoreDirector.java:120)
> 		at org.optaplanner.core.impl.score.DefaultScoreManager.updateScore(DefaultScoreManager.java:44)
> 		... 44 more

**Comment by triceo** [comment]
We are aware of the issue and are working on a fix:
https://github.com/kiegroup/drools/pull/3601

Thanks for reporting!

**Comment by triceo** [comment]
We believe the issue should be fixed now.
