### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by KobNael** [apache/incubator-kie-optaplanner-quickstarts#274]
Hi,
I'm trying to build and run the project, but I've got the following error : 

`[ERROR] No plugin found for prefix 'quarkus' in the current project and in the plugin groups`

I could not find any help on the subject, would you have any hint ?

Thx

**Comment by triceo** [comment]
@Christopher-Chianelli Can you please take a look?

**Comment by ge0ffrey** [comment]
@KobNael From which directory are you building the project? With which command are you building the project?

**Comment by ge0ffrey** [comment]
Reproduced:
Build from the root directory and run "mvn quarkus:dev".

@KobNael "mvn quarkus:dev" needs to be run in one of the use-cases subdirectories.
For example: cd use-cases/school-timetabling; mvn quarkus:dev

**Comment by ge0ffrey** [comment]
@KobNael Where did you see the information that led you to believe to run "mvn quarkus:dev" from the root directory? We'd like to improve that docs/readme/guide.

**Comment by KobNael** [comment]
thank you, that did the trick.   
It's my bad, I read the readme too fast.   
It's clearly written though :  `cd optaplanner-quickstarts/use-cases/maintenance-scheduling`   ...

**Comment by ge0ffrey** [comment]
Thanks for letting us know!
