### ISSUE TITLE
Micrometer Score Logging

### ISSUE THREAD

**Issue by guneetsk99** [apache/incubator-kie-optaplanner-quickstarts#425]
Hi Developers, I am trying to log custom metrics besides the one provided in the doc. Can you please point me to the part of the Optaplanner where you introduced the MIcrometer to manage Metrics discussed in the documentation? I could use it as a reference to solve my problem 
Thanks

**Comment by ge0ffrey** [comment]
Please use stackoverflow or our discussion forum for questions
https://www.optaplanner.org/community/getHelp.html

Answer: See BEST_SCORE monitoring here https://www.optaplanner.org/docs/optaplanner/latest/planner-configuration/planner-configuration.html#_additional_metrics
